### ISSUE TITLE
Replacing gurobi with an open source package

### ISSUE THREAD

**Issue by samburu** [joaopedroso/lnd_kaiyodai#1]
Hi @joaopedroso 

Awesome work. I would like to replace gurobi package with an open source one. Is there one you would recommend?

Thanks.

**Comment by joaopedroso** [comment]
Hello @samburu , thanks for your interest.
For an open source, non-free I would suggest SCIP, which has a similar Python interface: https://www.scipopt.org
Otherwise, using PuLP there is a range of solvers available: https://coin-or.github.io/pulp/
In both cases, adapting the code should be easy.

**Comment by samburu** [comment]
Thanks @joaopedroso  for the replay. What do you think of https://www.cvxpy.org/?

**Comment by joaopedroso** [comment]
Samburu,

> What do you think of https://www.cvxpy.org/?

I think it's excellent.  Its Python interface may be a bit different
from gurobi's, though...

jpp

**Comment by samburu** [comment]
Thanks @joaopedroso  for suggestions , `PuLP`  does  meet my needs.
